baseURL: https://xar.sh
languageCode: ja-jp
defaultContentLanguage: ja
title: xar.sh
hasCJKLanguage: true
permalinks:
  post: /post/:contentbasename/
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: "abap"
disableKinds:
  - taxonomy
taxonomies:
  category: categories
  tag: tags
